### ISSUE TITLE
YomiNinja doesn't work on Linux Mint

### ISSUE THREAD

**Issue by emanuelps2708** [matt-m-o/YomiNinja#29]
Hi, I installed YomiNinja with its dependencies following the guide, unfortunately it doesn't scan anything, I tried with different ocrs, images, videos and changing the hotkeys but it still doesn't work :c.

Here's the log after launching the program from the terminal 

```{
  ROOT_DIR: '/opt/YomiNinja/resources/app.asar/',
  PAGES_DIR: '/opt/YomiNinja/resources/app.asar/renderer/out',
  BIN_DIR: '/opt/YomiNinja/bin',
  EXTENSIONS_DIR: '/home/emanuel/.config/YomiNinja/extensions',
  USER_DATA_DIR: '/home/emanuel/.config/YomiNinja'
}
{
  dicPath: '/opt/YomiNinja/resources/app.asar/node_modules/kuromoji/dict'
}
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x7D621360B640!
Installing 10ten-ja-reader-1.15.1-chrome
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/10ten-ja-reader-1.15.1-chrome.zip'
    at unlinkSync (node:fs:1808:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at Object.rmSync (node:fs:1276:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:108:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:186:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:12:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:52:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:15:5) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/opt/YomiNinja/resources/extensions/10ten-ja-reader-1.15.1-chrome.zip'
}
Installing Google-Translate
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/Google-Translate.zip'
    at unlinkSync (node:fs:1808:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at Object.rmSync (node:fs:1276:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:108:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:186:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:12:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:52:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:15:5) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/opt/YomiNinja/resources/extensions/Google-Translate.zip'
}
Installing jpd-breader_13.0_yn
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/jpd-breader_13.0_yn.zip'
    at unlinkSync (node:fs:1808:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at Object.rmSync (node:fs:1276:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:108:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:186:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:12:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:52:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:15:5) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/opt/YomiNinja/resources/extensions/jpd-breader_13.0_yn.zip'
}
Installing yomitan-chrome-24.2.12.0
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/yomitan-chrome-24.2.12.0.zip'
    at unlinkSync (node:fs:1808:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at Object.rmSync (node:fs:1276:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:108:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:186:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:12:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:52:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:15:5) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/opt/YomiNinja/resources/extensions/yomitan-chrome-24.2.12.0.zip'
}
Error: Bad archive
    at FsRead.readUntilFoundCallback [as callback] (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:203:39)
    at FsRead.readCallback (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:996:25)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:682:5)
stdout: Notice: this application is experimental!!! 


 App settings preset root: /home/emanuel/.config/YomiNinja/ppocr/presets/

 App settings preset: default
{
    "cls_thresh": 0.9,
    "cpu_threads": 8,
    "det_db_box_thresh": 0.6,
    "det_db_score_mode": "slow",
    "det_db_thresh": 0.3,
    "det_db_unclip_ratio": 1.6,
    "inference_backend": "Open_VINO",
    "initialize_all_language_presets": false,
    "language_code": "ja",
    "language_presets": {
        "ch": "chinese_v4",
        "en": "english_v4",
        "ja": "japanese_v4",
        "ko": "korean_v4"
    },
    "max_image_width": 1600,
    "name": "default",
    "port": 12345,
    "use_dilation": true
}
language_code: ch, preset_name: chinese_v4
language_code: en, preset_name: english_v4
language_code: ja, preset_name: japanese_v4
language_code: ko, preset_name: korean_v4

 App settings preset root: /home/emanuel/.config/YomiNinja/ppocr/presets/

 App settings preset: default
{
    "cls_thresh": 0.9,
    "cpu_threads": 8,
    "det_db_box_thresh": 0.6,
    "det_db_score_mode": "slow",
    "det_db_thresh": 0.3,
    "det_db_unclip_ratio": 1.6,
    "inference_backend": "Open_VINO",
    "initialize_all_language_presets": false,
    "language_code": "ja",
    "language_presets": {
        "ch": "chinese_v4",
        "en": "english_v4",
        "ja": "japanese_v4",
        "ko": "korean_v4"
    },
    "max_image_width": 1600,
    "name": "default",
    "port": 12345,
    "use_dilation": true
}
language_code: ch, preset_name: chinese_v4
language_code: en, preset_name: english_v4

stdout: language_code: ja, preset_name: japanese_v4
language_code: ko, preset_name: korean_v4

initializing wih address: 0.0.0.0:12345
stdout: [INFO-JSON]:{"server_address":"0.0.0.0:12345"}

Error: 14 UNAVAILABLE: read ECONNRESET
    at callErrorFromStatus (/opt/YomiNinja/resources/app.asar/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/opt/YomiNinja/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/opt/YomiNinja/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/opt/YomiNinja/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /opt/YomiNinja/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/opt/YomiNinja/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.<anonymous> (/opt/YomiNinja/resources/app.asar/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at clientResponse (/opt/YomiNinja/resources/app.asar/main/electron-src/@core/infra/ocr/ppocr.adapter/ppocr.adapter.js:201:92)
    at new Promise (<anonymous>)
    at PpOcrAdapter.updateSettings (/opt/YomiNinja/resources/app.asar/main/electron-src/@core/infra/ocr/ppocr.adapter/ppocr.adapter.js:201:36)
    at async UpdateSettingsPresetUseCase.handleOcrAdapterSettingsUpdate (/opt/YomiNinja/resources/app.asar/main/electron-src/@core/application/use_cases/update_settings_preset/update_settings_preset.use_case.js:85:24)
    at async UpdateSettingsPresetUseCase.execute (/opt/YomiNinja/resources/app.asar/main/electron-src/@core/application/use_cases/update_settings_preset/update_settings_preset.use_case.js:31:33)
    at async initializeApp (/opt/YomiNinja/resources/app.asar/main/electron-src/@core/infra/app_initialization.js:77:13)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:57:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:15:5) {
  code: 14,
  details: 'read ECONNRESET',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
retrying: PpOcrAdapter.updateSettings
stdout: Saving settings...
Settings file path: /home/emanuel/.config/YomiNinja/ppocr/presets/default.json
{
    "name": "default",
    "language_presets": {
        "ch": "chinese_v4",
        "en": "english_v4",
        "ja": "japanese_v4",
        "ko": "korean_v4"
    },
    "language_code": "ja",
    "initialize_all_language_presets": false,
    "inference_backend": "Open_VINO",
    "cpu_threads": 8,
    "port": 12345,
    "max_image_width": 1600,
    "det_db_thresh": 0.3,
    "det_db_box_thresh": 0.6,
    "det_db_unclip_ratio": 1.6,
    "det_db_score_mode": "slow",
    "use_dilation": true,
    "cls_thresh": 0.9
}

stdout: Saving settings...
Settings file path: /home/emanuel/.config/YomiNinja/ppocr/presets/default.json
{
    "name": "default",
    "language_presets": {
        "ch": "chinese_v4",
        "en": "english_v4",
        "ja": "japanese_v4",
        "ko": "korean_v4"
    },
    "language_code": "ja",
    "initialize_all_language_presets": false,
    "inference_backend": "Open_VINO",
    "cpu_threads": 8,
    "port": 12345,
    "max_image_width": 1600,
    "det_db_thresh": 0.3,
    "det_db_box_thresh": 0.6,
    "det_db_unclip_ratio": 1.6,
    "det_db_score_mode": "slow",
    "use_dilation": true,
    "cls_thresh": 0.9
}

Loading extension from /home/emanuel/.config/YomiNinja/extensions/Brian Birtles.10ten Japanese Reader (Rikaichamp)
(node:515056) ExtensionLoadWarning: Warnings loading extension at /home/emanuel/.config/YomiNinja/extensions/Brian Birtles.10ten Japanese Reader (Rikaichamp):
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(Use `yomininja-e --trace-warnings ...` to show where the warning was created)
Loading extension from /home/emanuel/.config/YomiNinja/extensions/google-translate-chrome-extension-owners@google.com.__MSG_8969005060131950570__
(node:515056) ExtensionLoadWarning: Warnings loading extension at /home/emanuel/.config/YomiNinja/extensions/google-translate-chrome-extension-owners@google.com.__MSG_8969005060131950570__:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

Loading extension from /home/emanuel/.config/YomiNinja/extensions/themoeway@googlegroups.com.Yomitan
Loading extension from /home/emanuel/.config/YomiNinja/extensions/undefined.JPDBreader
(node:515056) ExtensionLoadWarning: Warnings loading extension at /home/emanuel/.config/YomiNinja/extensions/undefined.JPDBreader:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

[515189:0612/181314.034480:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
[515189:0612/181314.037748:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
[515189:0612/181314.038182:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
[515189:0612/181314.038847:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
[515189:0612/181314.039136:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
Error occurred in handler for 'app:get_active_capture_source': Error: No handler registered for 'app:get_active_capture_source'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89692)
    at WebContents.emit (node:events:513:28)
AppController.handleOcrCommand
AppController.handleOcrCommand
AppController.handleOcrCommand```

**Comment by matt-m-o** [comment]
It's likely that there is an issue with PaddleOCR, possibly conflicting with another process. I tested it on Linux Mint, and it worked fine. This problem should be resolved in v0.8, which can better handle these conflicts and run without PaddleOCR.

**Comment by emanuelps2708** [comment]
Oh ok, thank you, I'm looking forward to testing it. ;)

**Comment by madmalkav** [comment]
Can you please try with the last version and report if the issue persists?

**Comment by emanuelps2708** [comment]
Hi, thanks for the new release. I just installed it, however there's a problem. Now it won't open

```{
  ROOT_DIR: '/opt/YomiNinja/resources/app.asar/',
  PAGES_DIR: '/opt/YomiNinja/resources/app.asar/renderer/out',
  BIN_DIR: '/opt/YomiNinja/bin',
  EXTENSIONS_DIR: '/home/emanuelps27/.config/YomiNinja/extensions',
  USER_DATA_DIR: '/home/emanuelps27/.config/YomiNinja',
  ICONS_DIR: '/opt/YomiNinja/resources'
}
{
  dicPath: '/opt/YomiNinja/resources/app.asar/node_modules/kuromoji/dict'
}
{ cpu_model: 'AMD Ryzen 3 5300U with Radeon Graphics' }
{
  launchConfig: {
    hardware_acceleration: true,
    gpu_compositing: true,
    enable_devtools: true
  }
}

HTTP Server port: 10010
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x72CEA33216C0!
Installing 10ten-ja-reader-1.25.1-chrome-electron
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/10ten-ja-reader-1.25.1-chrome-electron.zip'
    at unlinkSync (node:fs:1953:11)
    at _unlinkSync (node:internal/fs/rimraf:215:14)
    at rimrafSync (node:internal/fs/rimraf:196:7)
    at Object.rmSync (node:fs:1248:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:115:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:205:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:13:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:75:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:35:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/opt/YomiNinja/resources/extensions/10ten-ja-reader-1.25.1-chrome-electron.zip'
}
Error: Bad archive
    at FsRead.readUntilFoundCallback [as callback] (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:198:39)
    at FsRead.readCallback (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:996:25)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:672:5)
Installing Google-Translate
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/Google-Translate.zip'
    at unlinkSync (node:fs:1953:11)
    at _unlinkSync (node:internal/fs/rimraf:215:14)
    at rimrafSync (node:internal/fs/rimraf:196:7)
    at Object.rmSync (node:fs:1248:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:115:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:205:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:13:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:75:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:35:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/opt/YomiNinja/resources/extensions/Google-Translate.zip'
}
Installing Zhongwen-Chinese-English-Dictionary-Chrome-Web-Store
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/Zhongwen-Chinese-English-Dictionary-Chrome-Web-Store.zip'
    at unlinkSync (node:fs:1953:11)
    at _unlinkSync (node:internal/fs/rimraf:215:14)
    at rimrafSync (node:internal/fs/rimraf:196:7)
    at Object.rmSync (node:fs:1248:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:115:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:205:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:13:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:75:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:35:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/opt/YomiNinja/resources/extensions/Zhongwen-Chinese-English-Dictionary-Chrome-Web-Store.zip'
}
Error: Bad archive
    at FsRead.readUntilFoundCallback [as callback] (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:203:39)
    at FsRead.readCallback (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:996:25)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:672:5)
Installing jpd-breader_13.0
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/jpd-breader_13.0.zip'
    at unlinkSync (node:fs:1953:11)
    at _unlinkSync (node:internal/fs/rimraf:215:14)
    at rimrafSync (node:internal/fs/rimraf:196:7)
    at Object.rmSync (node:fs:1248:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:115:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:205:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:13:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:75:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:35:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/opt/YomiNinja/resources/extensions/jpd-breader_13.0.zip'
}
Installing yomitan-chrome-25.7.14.1
Error: EACCES: permission denied, unlink '/opt/YomiNinja/resources/extensions/yomitan-chrome-25.7.14.1.zip'
    at unlinkSync (node:fs:1953:11)
    at _unlinkSync (node:internal/fs/rimraf:215:14)
    at rimrafSync (node:internal/fs/rimraf:196:7)
    at Object.rmSync (node:fs:1248:10)
    at BrowserExtensionManager.installBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extension_manager/browser_extension_manager.js:115:34)
    at async BrowserExtensionsService.handleBuiltinExtensions (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.service.js:205:9)
    at async BrowserExtensionsController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/extensions/browser_extensions.controller.js:13:9)
    at async AppController.init (/opt/YomiNinja/resources/app.asar/main/electron-src/app/app.controller.js:75:9)
    at async App.<anonymous> (/opt/YomiNinja/resources/app.asar/main/electron-src/index.js:35:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/opt/YomiNinja/resources/extensions/yomitan-chrome-25.7.14.1.zip'
}
Error: Bad archive
    at FsRead.readUntilFoundCallback [as callback] (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:203:39)
    at FsRead.readCallback (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:996:25)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:672:5)
(electron) 'session.getPreloads' is deprecated and will be removed. Please use 'session.getPreloadScripts' instead.
(electron) 'session.setPreloads' is deprecated and will be removed. Please use 'session.registerPreloadScript' instead.
(node:33486) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Namespace]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `yomininja-e --trace-warnings ...` to show where the warning was created)
listen EADDRINUSE: address already in use :::52000
(node:33486) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
listen EADDRINUSE: address already in use :::52001
listen EADDRINUSE: address already in use :::52002
listen EADDRINUSE: address already in use :::52003
stdout: Notice: this application is experimental!!! 


 App settings preset root: /home/emanuelps27/.config/YomiNinja/ppocr/presets/

 App settings preset: default
{
    "cls_thresh": 0.9,
    "cpu_threads": 24,
    "det_db_box_thresh": 0.6,
    "det_db_score_mode": "slow",
    "det_db_thresh": 0.3,
    "det_db_unclip_ratio": 1.6,
    "inference_backend": "ONNX_CPU",
    "initialize_all_language_presets": false,
    "language_code": "ja",
    "language_presets": {
        "cyrl": "cyrillic_v3",
        "en": "english_v4",
        "ja-JP": "japanese_v4",
        "ko-KR": "korean_v4",
        "la": "latin_v3",
        "zh-Hans": "chinese_simplified_v4",
        "zh-Hant": "chinese_traditional_v3"
    },
    "max_image_width": 1600,
    "name": "default",
    "port": 12345,
    "use_dilation": false
}
language_code: cyrl, preset_name: cyrillic_v3
language_code: en, preset_name: english_v4
language_code: ja-JP, preset_name: japanese_v4
language_code: ko-KR, preset_name: korean_v4
language_code: la, preset_name: latin_v3
language_code: zh-Hans, preset_name: chinese_simplified_v4

stdout: language_code: zh-Hant, preset_name: chinese_traditional_v3

 App settings preset root: /home/emanuelps27/.config/YomiNinja/ppocr/presets/

 App settings preset: default
{
    "cls_thresh": 0.9,
    "cpu_threads": 24,
    "det_db_box_thresh": 0.6,
    "det_db_score_mode": "slow",
    "det_db_thresh": 0.3,
    "det_db_unclip_ratio": 1.6,
    "inference_backend": "ONNX_CPU",
    "initialize_all_language_presets": false,
    "language_code": "ja",
    "language_presets": {
        "cyrl": "cyrillic_v3",
        "en": "english_v4",
        "ja-JP": "japanese_v4",
        "ko-KR": "korean_v4",
        "la": "latin_v3",
        "zh-Hans": "chinese_simplified_v4",
        "zh-Hant": "chinese_traditional_v3"
    },
    "max_image_width": 1600,
    "name": "default",
    "port": 12345,
    "use_dilation": false
}
language_code: cyrl, preset_name: cyrillic_v3
language_code: en, preset_name: english_v4
language_code: ja-JP, preset_name: japanese_v4
language_code: ko-KR, preset_name: korean_v4
language_code: la, preset_name: latin_v3
language_code: zh-Hans, preset_name: chinese_simplified_v4
language_code: zh-Hant, preset_name: chinese_traditional_v3

initializing PaddleOcrService | Address: 0.0.0.0:52004
stdout: [INFO-JSON]:{"server_address":"0.0.0.0:52004"}

stderr: /opt/YomiNinja/resources/bin/py_ocr_service/python/lib/python3.12/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.0 is exactly one major version older than the runtime version 6.31.1 at ocr_service.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

stderr: Traceback (most recent call last):
  File "/opt/YomiNinja/resources/bin/py_ocr_service/src/py_ocr_service.py", line 23, in <module>
    from manga_ocr_service.manga_ocr_service import MangaOcrService
  File "/opt/YomiNinja/resources/bin/py_ocr_service/src/manga_ocr_service/manga_ocr_service.py", line 9, in <module>
    from .comic_text_detector import ComicTextDetector
  File "/opt/YomiNinja/resources/bin/py_ocr_service/src/manga_ocr_service/comic_text_detector.py", line 5, in <module>
    from comic_text_detector.inference import TextDetector

stderr:   File "/opt/YomiNinja/resources/bin/py_ocr_service/src/comic_text_detector/inference.py", line 14, in <module>
    from comic_text_detector.utils.io_utils import imread, imwrite, find_all_imgs, NumpyEncoder
  File "/opt/YomiNinja/resources/bin/py_ocr_service/src/comic_text_detector/utils/io_utils.py", line 11, in <module>
    NP_BOOL_TYPES = (np.bool_, np.bool8)
                               ^^^^^^^^
  File "/home/emanuelps27/.local/lib/python3.12/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'
stderr: . Did you mean: 'bool'?

/bin/python3.12 process exited with code 1
```

I don't know what's the reason
