### ISSUE TITLE
OCR Engine stuck processing without showing anything

### ISSUE THREAD

**Issue by dblop** [matt-m-o/YomiNinja#35]
I'm trying this on endeavour // arch linux with v0.7.2, installed from the pacman release (X11 session w/ xdotools). Yomininja appears to launch fine and I can see the overlay, but when pressing to activate the engine it seems to be stuck (using Google Lens in this example but none works), I just see an infinite wheel at the bottom of the overlay like it was processing the request. 

Here is what I see from the terminal after running the yomininja command (alt+A to activate overlay, no other options clicked):

```
{
  ROOT_DIR: '/opt/YomiNinja/resources/app.asar/',
  PAGES_DIR: '/opt/YomiNinja/resources/app.asar/renderer/out',
  BIN_DIR: '/opt/YomiNinja/bin',
  EXTENSIONS_DIR: '/home/diego/.config/YomiNinja/extensions',
  USER_DATA_DIR: '/home/diego/.config/YomiNinja',
  ICONS_DIR: '/opt/YomiNinja/resources'
}
{
  dicPath: '/opt/YomiNinja/resources/app.asar/node_modules/kuromoji/dict'
}
[244276:0804/130854.205423:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[244276:0804/130854.205458:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x7C35EEE006C0!
load_input_helper [1827]: XkbGetKeyboard failed to locate a valid keyboard!
[244276:0804/130854.231304:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
Error: Bad archive
    at FsRead.readUntilFoundCallback [as callback] (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:203:39)
    at FsRead.readCallback (/opt/YomiNinja/resources/app.asar/node_modules/node-stream-zip/node_stream_zip.js:996:25)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:682:5)
stdout: Notice: this application is experimental!!! 


 App settings preset root: /home/diego/.config/YomiNinja/ppocr/presets/

stdout: 
 App settings preset: default
{
    "cls_thresh": 0.9,
    "cpu_threads": 24,
    "det_db_box_thresh": 0.6,
    "det_db_score_mode": "slow",
    "det_db_thresh": 0.3,
    "det_db_unclip_ratio": 1.6,
    "inference_backend": "Open_VINO",
    "initialize_all_language_presets": false,
    "language_code": "ja",
    "language_presets": {
        "cyrl": "cyrillic_v3",
        "en": "english_v4",
        "ja-JP": "japanese_v4",
        "ko-KR": "korean_v4",
        "la": "latin_v3",
        "zh-Hans": "chinese_simplified_v4",
        "zh-Hant": "chinese_traditional_v3"
    },
    "max_image_width": 1600,
    "name": "default",
    "port": 12345,
    "use_dilation": false
}
language_code: cyrl, preset_name: cyrillic_v3
language_code: en, preset_name: english_v4
language_code: ja-JP, preset_name: japanese_v4
language_code: ko-KR, preset_name: korean_v4
language_code: la, preset_name: latin_v3
language_code: zh-Hans, preset_name: chinese_simplified_v4
language_code: zh-Hant, preset_name: chinese_traditional_v3

 App settings preset root: /home/diego/.config/YomiNinja/ppocr/presets/

 App settings preset: default
{
    "cls_thresh": 0.9,
    "cpu_threads": 24,
    "det_db_box_thresh": 0.6,
    "det_db_score_mode": "slow",
    "det_db_thresh": 0.3,
    "det_db_unclip_ratio": 1.6,
    "inference_backend": "Open_VINO",
    "initialize_all_language_presets": false,
    "language_code": "ja",
    "language_presets": {
        "cyrl": "cyrillic_v3",
        "en": "english_v4",
        "ja-JP": "japanese_v4",
        "ko-KR": "korean_v4",
        "la": "latin_v3",
        "zh-Hans": "chinese_simplified_v4",
        "zh-Hant": "chinese_traditional_v3"
    },
    "max_image_width": 1600,
    "name": "default",
    "port": 12345,
    "use_dilation": false
}
language_code: cyrl, preset_name: cyrillic_v3
language_code: en, preset_name: english_v4
language_code: ja-JP, preset_name: japanese_v4
language_code: ko-KR, preset_name: korean_v4
language_code: la, preset_name: latin_v3
language_code: zh-Hans, preset_name: chinese_simplified_v4
language_code: zh-Hant, preset_name: chinese_traditional_v3

initializing wih address: 0.0.0.0:12345
stdout: [INFO-JSON]:{"server_address":"0.0.0.0:12345"}

MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/dri, suffix _dri)
stdout: [INFO-JSON]:{"server_address": "0.0.0.0:23456"}

Initializing PyOcrService | Address: 0.0.0.0:23456
stdout: Saving settings...
Settings file path: /home/diego/.config/YomiNinja/ppocr/presets/default.json
{
    "name": "default",
    "language_presets": {
        "cyrl": "cyrillic_v3",
        "en": "english_v4",
        "ja-JP": "japanese_v4",
        "ko-KR": "korean_v4",
        "la": "latin_v3",
        "zh-Hans": "chinese_simplified_v4",
        "zh-Hant": "chinese_traditional_v3"
    },
    "language_code": "ja",
    "initialize_all_language_presets": false,
    "inference_backend": "ONNX_CPU",
    "cpu_threads": 16,
    "port": 12345,
    "max_image_width": 1600,
    "det_db_thresh": 0.3,
    "det_db_box_thresh": 0.6,
    "det_db_unclip_ratio": 1.6,
    "det_db_score_mode": "slow",
    "use_dilation": false,
    "cls_thresh": 0.9
}

stdout: Saving settings...
Settings file path: /home/diego/.config/YomiNinja/ppocr/presets/default.json
{
    "name": "default",
    "language_presets": {
        "cyrl": "cyrillic_v3",
        "en": "english_v4",
        "ja-JP": "japanese_v4",
        "ko-KR": "korean_v4",
        "la": "latin_v3",
        "zh-Hans": "chinese_simplified_v4",
        "zh-Hant": "chinese_traditional_v3"
    },
    "language_code": "ja",
    "initialize_all_language_presets": false,
    "inference_backend": "ONNX_CPU",
    "cpu_threads": 16,
    "port": 12345,
    "max_image_width": 1600,
    "det_db_thresh": 0.3,
    "det_db_box_thresh": 0.6,
    "det_db_unclip_ratio": 1.6,
    "det_db_score_mode": "slow",
    "use_dilation": false,
    "cls_thresh": 0.9
}

Loading extension from /home/diego/.config/YomiNinja/extensions/Brian Birtles.10ten Japanese Reader (Rikaichamp)
(node:244276) ExtensionLoadWarning: Warnings loading extension at /home/diego/.config/YomiNinja/extensions/Brian Birtles.10ten Japanese Reader (Rikaichamp):
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(Use `yomininja-e --trace-warnings ...` to show where the warning was created)
Loading extension from /home/diego/.config/YomiNinja/extensions/google-translate-chrome-extension-owners@google.com.__MSG_8969005060131950570__
(node:244276) ExtensionLoadWarning: Warnings loading extension at /home/diego/.config/YomiNinja/extensions/google-translate-chrome-extension-owners@google.com.__MSG_8969005060131950570__:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

Loading extension from /home/diego/.config/YomiNinja/extensions/themoeway@googlegroups.com.Yomitan
Loading extension from /home/diego/.config/YomiNinja/extensions/undefined.JPDBreader
(node:244276) ExtensionLoadWarning: Warnings loading extension at /home/diego/.config/YomiNinja/extensions/undefined.JPDBreader:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

Error occurred in handler for 'app:get_active_capture_source': Error: No handler registered for 'app:get_active_capture_source'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89692)
    at WebContents.emit (node:events:513:28)
[244473:0804/130855.993737:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
[244473:0804/130855.993805:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
[244473:0804/130855.993991:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
[244473:0804/130855.998498:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
[244473:0804/130855.998565:ERROR:native_extension_bindings_system.cc(600)] Failed to create API on Chrome object.
YomiNinja Startup time: 1.777s
{ isAutoOcrEnabled: false }
{ isAutoOcrEnabled: false }
{ isAutoOcrEnabled: false }
[244276:0804/130856.436376:ERROR:extensions_browser_client.cc(69)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://hlihljenffkekoihahcjnkjbingfhgao/js/background/backend.js
  Message: Uncaught (in promise) TypeError: chrome.tabs.create is not a function
  ID:      hlihljenffkekoihahcjnkjbingfhgao
  Type:    RuntimeError
  Context: chrome-extension://hlihljenffkekoihahcjnkjbingfhgao/js/background/backend.js
  Stack Trace: 
    {
      Line:     2537
      Column:   1
      URL:      chrome-extension://hlihljenffkekoihahcjnkjbingfhgao/js/background/backend.js
      Function: (anonymous function)
    }
[244276:0804/130904.173939:ERROR:screen_capture_portal_interface.cc(78)] Failed to request the session subscription.
[244276:0804/130904.173955:ERROR:base_capturer_pipewire.cc(81)] ScreenCastPortal failed: 3
(node:244276) UnhandledPromiseRejectionWarning: Failed to get sources.
(node:244276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by madmalkav** [comment]
Can you please try with the last version and report if the issue persists?
