### ISSUE TITLE
Yomitan API issue?

### ISSUE THREAD

**Issue by Hisayoo** [matt-m-o/YomiNinja#45]
I am trying to get yomininja to work with Yomitan but when I try to OCR with PaddleOCR this happens and gets spammed on my desktop. Using Windows 11 Pro
```Error: invalid API key while parsing 「G sanc G tatoe G cl…」
Error: invalid API key while parsing 「G sanc G tatoe G cl…」
    at Module.parse (chrome-extension://dbbmcpikkgkjbjpegecengihoincocem/background/backend.js:39:15)
    at async Object.batchParses [as func] (chrome-extension://dbbmcpikkgkjbjpegecengihoincocem/background/background.js:70:44)
    at async apiCaller (chrome-extension://dbbmcpikkgkjbjpegecengihoincocem/background/background.js:19:36)```

This is what happens with MangaOCR: ```Error: invalid API key while parsing 「８／２７／２０２４ ＵＳ ・ ＾ ．．…」
Error: invalid API key while parsing 「８／２７／２０２４ ＵＳ ・ ＾ ．．…」
    at Module.parse (chrome-extension://dbbmcpikkgkjbjpegecengihoincocem/background/backend.js:39:15)
    at async Object.batchParses [as func] (chrome-extension://dbbmcpikkgkjbjpegecengihoincocem/background/background.js:70:44)
    at async apiCaller (chrome-extension://dbbmcpikkgkjbjpegecengihoincocem/background/background.js:19:36)```

**Comment by Hisayoo** [comment]
It was because I ocr'd with the jpdb extension enabled while not providing an API key in the extension settings.
